spring:
  cache:
    # 指定缓存类型，缓存类型不再是EhCache了，EhCache3是实现JCache的一种缓存，jcache支持： ehcache3  redis等
    # 配置了spring.cache.jcache.config属性会自动装配JCacheCacheManager
    type: jcache
    # 这个文件名可以自己定义
    jcache.config: classpath:ehcache3.xml
    redis:
      time-to-live: 1h
    # Cannot find cache named 'user' for Builder[public java.util.List com.cmmplb.cache.service.impl.UserServiceImpl.list()]
    # caches=[user] | key='' | keyGenerator='customKeyGenerator' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'
    cache-names:
      - user

# 使用ehcache的时候关闭，用配置文件创建CacheManager
cache:
  enabled: false
  cache-type: ehcache