spring:
  jpa:
    show-sql: true # 默认false，在日志里显示执行的sql语句
    database: mysql
    # ddl-auto的几种属性值
      # none
      # create：每次加载hibernate时都会删除上一次的生成的表，再重新根据model生成表，因此可能会导致数据丢失。
      # create-drop ：每次加载hibernate时根据model类生成表，但是sessionFactory一关闭，表就自动删除。
      # update：最常用的属性，第一次加载hibernate时根据model类会自动建立起表的结构（前提是先建立好数据库），以后加载hibernate时根据 model类自动更新表结构，原有数据不会清空，只会更新。
      # validate ：每次加载hibernate时，会校验数据与数据库的字段类型是否相同，字段不同会报错。
    hibernate.ddl-auto: none
    #在建表的时候，将默认的存储引擎切换为 InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true #关闭懒加载
