mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名->查出的字段转java驼峰-> create_time -> createTime
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql打印-配合mybatis-log-debug模式启动就能看到打印的日志
    # 开启二级缓存
    cache-enabled: true #使全局的映射器启用或禁用缓存. 
  global-config:
    #逻辑删除配置 3.0以上已开启实体类配置 使用mp自带方法删除和查找都会附带逻辑删除功能 (自己写的xml不会)
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    #关闭启动logo
    banner: false
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mapper/*/*.xml
  type-aliases-package: io.github.cmmplb.flyway.entity  # type-aliases扫描路径-mapper.xml的resultType中直接写类名, 可以不用写全限定名
  type-enums-package: io.github.cmmplb.flyway.enums # 配置通用枚举包


