version: '3.1'
services:
  canal:
    image: canal/canal-admin:v1.1.4
    restart: always
    container_name: canal-admin
    ports:
      - 8089:8089
    environment:
      - server.port=8089
      # canal连接所用的账号密码
      - canal.adminUser=admin
      - canal.adminPasswd=admin
      - spring.datasource.address=172.19.0.3:3306
      - spring.datasource.database=canal_admin
      - spring.datasource.username=root
      - spring.datasource.password=cmmplb
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://172.19.0.3:3306/canal_admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #这个挂载有问题，会导致容器里的文件隐藏，导致配置不了，注释掉，手动进入容器配置，docker exec -it <容器名称/ID> /bin/bash 
    #或者拷贝出来：docker cp 镜像id:容器文件夹或文件路径 宿主机路径
    #docker cp 镜像id:/home/admin/canal-admin/logs ./data/logs
    #docker cp 镜像id:/home/admin/canal-admin/conf ./data/conf
    #volumes:
      #- ./data/logs/:/home/admin/canal-admin/logs/
      #- ./data/conf/:/home/admin/canal-admin/conf/
    networks:
      - cmmplb
networks:
  cmmplb:
    external: true
