spring:
  artemis:
    mode: native
    host: ${ARTEMIS_HOST:localhost} # artermis连接地址
    port: ${ARTEMIS_PORT:9876} # artermis连接端口
    user: ${ARTEMIS_USER:admin} # 用户名
    password: ${ARTEMIS_PASSWORD:admin} # 密码
    send-timeout: # 发送超时时间
    pool:
      enabled: false # 是否创建 JmsPoolConnectionFactory 连接池
      idle-timeout: 30s # 空闲连接超时时间
      max-connections: 50 # 连接池中最大连接数
      max-sessions-per-connection: 100 # 每个连接最大会话