# knife4j配置
knife4j:
  # 开启knife4j增强
  enable: true
  # 是否是生产环境, 默认false，为true之后swagger相关资源接口请求会返回You do not have permission to access this page
  production: false
  # Basic认证
  basic:
    enable: false
    # Basic认证用户名
    username: admin
    # Basic认证密码-不配置默认账号admin/123321
    password: admin

    # springdoc-openapi项目配置
    #springdoc:
    #  swagger-ui:
    # 该参数是swagger默认的排序规则，如果设置为alpha，那么Knife4j提供的按照order排序的增强规则不生效，alpha:按照字母顺序排序，
    # 使用增强order属性排序扩展规则`x-order`进行排序，或者不设置该参数
    # 类排序
    #    tags-sorter: order
    # 方法排序
#    operations-sorter: order

# swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 分组名称
  group-name: @project.artifactId@
  # 标题
  title: @project.artifactId@ Swagger API
  # 描述
  description: description
  # 版本
  version: @project.version@
  # 许可证
  license: license
  # 许可证URL
  licenseUrl: licenseUrl
  # 服务条款URL
  terms-of-service-url: terms-of-service-url
  # host信息
  host:
  # 联系人信息
  contact:
    # 联系人
    name: penglibo
    url: https://gitee.com/cmmplb
    email: cmmplb@163.com