knife4j:
  enable: true  #开启增强功能
  basePackage: @project.groupId@ #swagger会解析的包路径
  groupName: @project.parent.groupId@   #分组名称
  title: ${spring.application.name}  #标题
  description: @project.description@ #描述
  version: @project.version@ #版本
  license: ... #许可证
  licenseUrl: ... #许可证URL
  termsOfServiceUrl: ... #服务条款URL
  host: 127.0.0.1 #host信息
  contact: #联系人信息
    name: cmmplb  #联系人
    url: www.cmmplb.com  #联系人url
    email: cmmplb@.com #联系人email