{{- if .Values.service.enabled }}
# 资源版本
apiVersion: v1
# 资源类型:Service
kind: Service
# 元数据
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
  # 标签选择器，用于确定当前service代理哪些pod
  labels:
  {{ include "service.labels.standard" . | indent 4 }}
spec:
  # ClusterIP分配一个集群内部可访问的固定虚拟IP
  # clusterIP: None
  type: NodePort
  ports:
    # 暴露端口
    - port: {{ .Values.service.port }}
      # 在本地开启31035的端口 将service暴露出来
      nodePort: {{ .Values.service.nodePort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
      # 应用真实的地址， 可以不写，默认和port一致
      targetPort: {{ .Values.service.port }}
  selector:
{{ include "service.labels.standard" . | indent 4 }}
    project: {{ .Values.namespace }}
    # 路由选择，标签为rabbitmq的应用 所以得修改pod上发布物yaml，将其打上标签
    app: {{ .Values.service.name }}
{{- end }}
