spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer #group-id将消费者进行分组（你也可以不进行分组）
      #消息读取策略，包含四个可选值：
      #earliest:当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费
      #latest:当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据
      #none:topic各分区都存在已提交的offset时，从offset后开始消费；只要有一个分区不存在已提交的offset，则抛出异常
      #exception:直接抛出异常
      auto-offset-reset: latest
