shiro:
  split: true #前后端分离
  whitelist: #白名单
    - /css/**
    - /js/**
    - /favicon.ico
    - /doc.html
    - /webjars/**           #swagger相关资源
    - /swagger-ui.html
    - /swagger-resources/**
    - /v3/api-docs/**       #v2改成v3了
    - /druid/**             #druid数据源监控页面不拦截
    - /logout               #配置退出过滤器，其中具体的退出代码Shiro已经替我们实现了
    - /basic/**             #基础管理里面的接口都放行
    - /login/do             #放行登录请求