<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!-- 父工程 -->
    <parent>
        <artifactId>spring-boot-webservice</artifactId>
        <groupId>io.github.cmmplb</groupId>
        <version>${revision}</version>
    </parent>
    <!-- 指定当前POM模型的版本 -->
    <modelVersion>4.0.0</modelVersion>
    <!-- 项目的唯一的标识符, 实际对应项目的名称, 就是项目根目录的名称。 -->
    <artifactId>spring-boot-webservice-server</artifactId>
    <!-- 项目的打包类型：pom、jar、war -->
    <packaging>jar</packaging>
    <!-- 项目名称 -->
    <name>${project.artifactId}</name>
    <!-- 描述信息 -->
    <description>${project.artifactId}</description>

    <!-- 依赖 -->
    <dependencies>
        <!-- web模块 -->
        <dependency>
            <groupId>io.github.cmmplb</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!--
            JAX-WS ( Java API for XML Web Services ) 规范是一组 XML web services 的 JAVA API
            JAX-WS 允许开发者可以选择 RPC-oriented 或者 message-oriented 来实现自己的 web services
        -->
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-spring-boot-starter-jaxws</artifactId>
            <version>${cxf-spring-boot-starter-jaxws.version}</version>
        </dependency>

    </dependencies>
</project>