thread:
  pool:
    - threadName: one
      threadNamePrefix: one-
      corePoolSize: 3
      maxPoolSize: 3

    - threadName: two
      threadNamePrefix: two-
      corePoolSize: 3
      maxPoolSize: 3
