# swagger增强配置，文档地址：https://doc.xiaominfo.com/knife4j/documentation/
knife4j:
  # 开启增强配置
  enable: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: false
    # Basic认证用户名
    username: momo
    # Basic认证密码-不配置默认账号admin/123321
    password: momo