<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!-- 父工程 -->
    <parent>
        <artifactId>spring-integration-boot</artifactId>
        <groupId>io.github.cmmplb</groupId>
        <version>${revision}</version>
    </parent>
    <!-- 指定当前POM模型的版本 -->
    <modelVersion>4.0.0</modelVersion>
    <!-- 项目的唯一的标识符, 实际对应项目的名称, 就是项目根目录的名称。 -->
    <artifactId>spring-boot-spark</artifactId>
    <!-- 项目的打包类型：pom、jar、war -->
    <packaging>jar</packaging>
    <!-- 项目名称 -->
    <name>${project.artifactId}</name>
    <!-- 描述信息 -->
    <description>${project.artifactId}</description>

    <!-- 依赖 -->
    <dependencies>
        <!-- web 模块 -->
        <dependency>
            <groupId>io.github.cmmplb</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Spark 依赖 -->
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.13</artifactId>
            <!-- 排除 log4j 依赖 -->
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-slf4j-impl</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.13</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_2.13</artifactId>
        </dependency>
        <!--
            Java 字节码生成引擎, 用于在运行时动态编译和执行 Java 代码. 它将 Java 源代码直接转换为字节码 ( .class 文件 ), 无需依赖外部
            编译器 ( 如 javac ), 从而实现动态代码生成和即时编译功能
        -->
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>janino</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
    </dependencies>
</project>