version: '3.1'
services:
  rabbitmq-master:
    image: rabbitmq:3.8.19-management
    restart: always
    container_name: rabbitmq-cluster-master
    hostname: rabbitmq-cluster-master
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST="/"
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=cmmplb
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
      # - ./data/log:/var/log/rabbitmq/log
      #配置文件也可以手动拷贝：docker cp 镜像id:容器文件夹或文件路径 宿主机路径
      #docker exec -it 镜像id /bin/sh    这种方式进入容器
      #docker cp 镜像id:/var/log/rabbitmq/log ./data/log
    networks:
      - cmmplb

  rabbitmq-slave1:
    image: rabbitmq:3.8.19-management
    restart: always
    container_name: rabbitmq-slave1
    hostname: rabbitmq-slave1
    ports:
      - 5674:5672
      - 15674:15672
    links:
      - rabbitmq-master
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq-master
      - RAM_NODE=true
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=cmmplb
    networks:
      - cmmplb

  rabbitmq-slave2:
    image: rabbitmq:3.8.19-management
    restart: always
    container_name: rabbitmq-slave2
    hostname: rabbitmq-slave2
    ports:
      - 5675:5672
      - 15675:15672
    links:
      - rabbitmq-master
      - rabbitmq-slave1
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq-master
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=cmmplb
    networks:
      - cmmplb

networks:
  cmmplb:
    external: true