INSERT INTO `user` (`tenant_id`,
                    `name`,
                    `sex`,
                    `mobile`,
                    `status`,
                    `create_time`,
                    `update_time`,
                    `version`,
                    `deleted`)
VALUES (1,
        '小明',
        1,
        '13999999999',
        0,
        NOW(),
        NOW(),
        1,
        0),
       (2,
        '小芳',
        0,
        '14999999999',
        1,
        NOW(),
        NOW(),
        1,
        0);