server:
  #undertow容器配置
  undertow:
    buffer-size: 1024  # 会用于服务器连接的IO操作
    #buffers-per-region: 1024      # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region   TODO: 过时属性
    direct-buffers: true  # 是否分配的直接内存(NIO直接分配的堆外内存)
    threads:
      io: 16  # 非阻塞的任务线程池：默认为CPU核心数量
      worker: 256 # 阻塞任务线程池: 默认为 IO线程数 * 8
