spring:
  rabbitmq:
    # 集群配置，以逗号分隔的客户端应连接的地址列表。设置后，主机和端口将被忽略。
    addresses: 192.168.68.129:5673,192.168.68.129:5674,192.168.68.129:5675
    host: 192.168.68.129
    port: 5672
    username: root
    password: cmmplb
    #相当于db配置=如果不存在的话需要去admin端添加
    virtual-host: spring-boot-rabbitmq
    #开启消息二次确认,生产者到broker的交换机
    publisher-confirm-type: correlated
    #开启消息二次确认，交换机到队列的可靠性投递
    publisher-returns: true
    template:
      #为true,则交换机处理消息到路由失败，则会返回给生产者
      mandatory: true
    listener:
      simple:
        #消费端
        concurrency: 5
        #最大消费端数
        max-concurrency: 10
        #自动签收auto 手动 manual
        acknowledge-mode: manual
        #限流（海量数据，同时只能过来一条）
        prefetch: 1
      direct:
        #消息手工确认ACK，自动签收auto (NONE,AUTO,MANUAL)
        acknowledge-mode: manual
