#canal配置
canal:
  client:
    instances:
      example:
        host: 192.168.68.129
        port: 11111
        # 账号canal-admin application.yml 设置的
        username: admin
        # 密码
        password: cmmplb
        #实例名称
        instance: example