# Failed to start bean 'documentationPluginsBootstrapper'
# 从Spring Boot 2.6开始，默认的匹配策略已经改为PathPatternParser
# AntPathMatcher：这种策略支持通配符如*（匹配任意字符序列）和**（匹配任意深度的目录结构）
#    例如，/api/users/**可以匹配到/api/users/123或/api/users/profile等任何以/api/users/开头的路径。
# PathPatternParser：更高效的路径匹配策略
# 特点和改进：
# 主要特性
# 1、性能提升：PathPatternParser经过优化，通常比AntPathMatcher更快，尤其是在处理大量路由规则时，这归功于其内部更高效的数据结构和算法。
# 2、更丰富的匹配模式：
#       支持命名捕获组（Named Captures），允许直接通过名称引用匹配的部分，而不仅仅是位置序号。
#       提供了更精细的控制选项，如忽略大小写匹配、严格模式匹配等。
#       支持更复杂的路径模式，包括精确匹配、通配符匹配、以及正则表达式风格的匹配规则。
# 3、路径段匹配：它以路径段（path segment）为单位进行匹配，而非简单的字符串比较，这使得匹配逻辑更加清晰和高效。
# 4、路径参数增强：除了基本的路径变量匹配外，还支持更复杂的路径参数模式，例如可选参数、重复参数模式等。
# 5、更直观的错误报告：当路径不匹配时，它可以提供更详细的错误信息，帮助开发者快速定位问题。

spring.mvc.pathmatch.matching-strategy: ant_path_matcher

# swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # swagger会解析的包路径
  base-package: com.cmmplb
  # 请求头
  header-list:
  # swagger会解析的url规则
  base-path:
  # 在basePath基础上需要排除的url规则
  exclude-path:
  # 分组名称
  group-name: cmmplb
  # 标题
  title: @project.artifactId@ Swagger API
  # 描述
  description: description
  # 版本
  version: @project.version@
  # 许可证
  license: license
  # 许可证URL
  licenseUrl: licenseUrl
  # 服务条款URL
  terms-of-service-url: terms-of-service-url
  # host信息
  host:
  # 联系人信息
  contact:
    # 联系人
    name: momo
    url: url
    email: email
  # 全局统一鉴权配置
  authorization:
    # 鉴权策略ID，需要和SecurityReferences ID保持一致，否则无法在请求头部参数渲染
    name: momo_assess_token
    # 需要开启鉴权URL的正则
    auth-regex: ^.*$
    # 认证类型-默认关闭-开启在左侧菜单显示认证
    # none-无认证
    # param-param模式-需要配置parameterList
    # implicit-简化模式
    # authorization_code-授权码模式
    # password-oauth2-密码模式
    # client_credentials-oauth2-客户端模式
    type: param
    parameter-list:
      # 简单模式参数
      - # 参数key
        parameterKeyName: token
        # 参数名称
        parameterName: token
        # 参数类型：query,header,path,cookie,form,formData,body
        parameterType: header
      - # 参数key
        parameterKeyName: Bear
        # 参数名称
        parameterName: Bear
        # 参数类型：query,header,path,cookie,form,formData,body
        parameterType: header
    client:
      client-id: momo_cloud
      client-secret: 123456
      # 简化/授权码模式认证url:http://xxx/xxx/oauth/authorize
      url: http://localhost:@gateway.port@/auth/oauth/authorize
    # 权限认证调用服务的 Api,如：http://xxx/xxx/login
    token-url-list:
      - http://localhost:@gateway.port@/auth/oauth/token
    # 鉴权作用域列表
    authorization-scope-list:
      # 作用域名称
      - scope: server
        # 作用域描述
        description: server all