# knife4j配置
knife4j:
  # 开启增强配置，默认false，自2.0.6版本后,只需要在配置文件中配置knife4j.enable=true即可不在使用注解@EnableKnife4j
  enable: true
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    # 该参数是swagger默认的排序规则，如果设置为alpha，那么Knife4j提供的按照order排序的增强规则不生效，alpha:按照字母顺序排序，
    # 使用增强order属性排序扩展规则`x-order`进行排序，或者不设置该参数
    # 类排序
    tags-sorter: order
    # 方法排序
    operations-sorter: order
# swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # swagger会解析的包路径集合
  packages-to-scan:
  # 排除的包路径
  packages-to-exclude:
  # swagger会解析的url规则集合
  paths-to-match:
  # 在basePath基础上需要排除的url规则集合
  paths-to-exclude:
  # 分组名称
  group-name: spring-boot-mybatis-mapper
  # 标题
  title: @project.artifactId@ Swagger API
  # 描述
  description: description
  # 版本
  version: @project.version@
  # 许可证
  license: license
  # 许可证URL
  licenseUrl: licenseUrl
  # 服务条款URL
  terms-of-service-url: terms-of-service-url
  # host信息
  host:
  # 联系人信息
  contact:
    # 联系人
    name: momo
    url: url
    email: email
  # 全局统一鉴权配置
  authorization:
    # 认证类型-默认关闭-开启在左侧菜单显示认证
    # none-无认证
    # param-param模式-需要配置parameterList
    # 简化模式和授权码模式需要配置回调地址：http://host:port/webjars/oauth/oauth2.html
    # implicit-简化模式
    # authorization_code-授权码模式
    # password-oauth2-密码模式
    # client_credentials-oauth2-客户端模式
    type: NONE
    parameter-list:
      # 简单模式参数
      - # 参数key
        parameterKeyName: token
        # 参数名称
        parameterName: token
        # 参数类型：query,header,path,cookie,form,formData,body
        parameterType: header
      - # 参数key
        parameterKeyName: Bear
        # 参数名称
        parameterName: Bear
        # 参数类型：query,header,path,cookie,form,formData,body
        parameterType: header
    # 认证url
    authorization-url: http://localhost:10000/auth/oauth/authorize
    # 权限认证调用服务api
    token-url: http://localhost:10000/auth/oauth/token
    # 刷新令牌url
    refresh-url: http://localhost:10000/auth/oauth/token
    # 鉴权作用域列表
    authorization-scope-list:
      # 作用域名称
      - scope: username
        # 作用域描述
        description: 获取用户信息