mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名->查出的字段转java驼峰-> create_time -> createTime
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql打印-配合mybatis-log-debug模式启动就能看到打印的日志
    # 开启二级缓存
    cache-enabled: true #使全局的映射器启用或禁用缓存. 
#    lazy-loading-enabled: true #全局启用或禁用延迟加载. 当禁用时, 所有关联对象都会即时加载
#    aggressive-lazy-loading: true #当启用时, 有延迟加载属性的对象在被调用时将会完全加载任意属性. 否则, 每种属性将会按需要加载
#    multiple-result-sets-enabled: true #是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true
#    use-column-label: true #是否可以使用列的别名 (取决于驱动的兼容性) default:true
#    use-generated-keys: true #允许JDBC 生成主键. 需要驱动器支持. 如果设为了true, 这个设置将强制使用被生成的主键, 有一些驱动器不兼容不过仍然可以执行.   default:false
#    auto-mapping-behavior: partial #指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射\u3000PARTIAL:部分  FULL:全部
#    default-executor-type: simple #这是默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
#    local-cache-scope: session #设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (这样就不会有数据的共享 ) defalut:session
  global-config:
    #逻辑删除配置 3.0以上已开启实体类配置 使用mp自带方法删除和查找都会附带逻辑删除功能 (自己写的xml不会)
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    #关闭启动logo
    banner: false
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mapper/*/*.xml
  type-aliases-package: io.github.cmmplb.mybatis.plus.entity  # type-aliases扫描路径-mapper.xml的resultType中直接写类名, 可以不用写全限定名
  type-enums-package: io.github.cmmplb.mybatis.plus.enums # 配置通用枚举包

