spring:
  velocity:
    enabled: true
    cache: false
    charset: UTF-8
    prefix: /templates/
    suffix: .vm
    content-type: text/html
    check-template-location: true
    resource-loader-path: /templates