seata:
  enabled: true
  application-id: applicationName
  tx-service-group: my_test_tx_group
  #如果你引入的是seata-all,请不要使用@EnableAutoDataSourceProxy注解。
  #如果你引入的是seata-spring-boot-starter 请关闭自动代理。
  enable-auto-data-source-proxy: false   #一定要是false
  service:
    vgroup-mapping:
      my_test_tx_group: default  #key与上面的tx-service-group的值对应
    grouplist:
      default: 127.0.0.1:8091 #seata-server地址仅file注册中心需要
  config:
    type: file
  registry:
    type: file
