spring:
  application.name: @project.name@
  profiles.include: compression, jetty, logging, tomcat, undertow, port
  profiles:
    active: dev
server:
  #port: @project.port@
  servlet.context-path: /api/@project.artifactId@
  compression.enabled: true
  tomcat:
    uri-encoding: UTF-8
    basedir: D:/Logs/tomcat/tmp