spring:
  datasource:
    username: root
    password: cmmplb
    url: jdbc:mysql://localhost:3306/spring-integration?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: appHikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 180000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      connection-test-query: SELECT 1
