xxl:
  job:
    executor:
      appname: xxl-job-executor-sample
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: cmmplb
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin