mybatis-plus:
  configuration:
    # 开启驼峰命名->查出的字段转java驼峰-> create_time -> createTime
    map-underscore-to-camel-case: true
    # 开启sql打印-配合mybatis-log-debug模式启动就能看到打印的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #关闭启动logo
    banner: false
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mapper/*/*.xml

